### PR TITLE
33...........

### PR DESCRIPTION
**Pull request by ravench**
I'm Stupid. (or It's just not a good idea to commit in between tasks at EMFcamp)

### CODE REVIEW

**Comment by The-Compiler** [comment]
While you're at it, "Externel Flash" should be "External" and "Tripod" should be indented correctly :wink:

**Comment by ravench** [comment]
That indenting is intentional - while a tripod is camera gear, it's not part of a camera.

**Comment by The-Compiler** [comment]
Neither is the charger, or the camera bag, or lots of the other stuff listed there.

**Comment by ravench** [comment]
In a world where every camera requires a different charger and an size bag....

**Pull request merged**
